// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TestService_CheckActive_FullMethodName           = "/proto.TestService/CheckActive"
	TestService_HealthCheck_FullMethodName           = "/proto.TestService/HealthCheck"
	TestService_Hello_FullMethodName                 = "/proto.TestService/Hello"
	TestService_PrintBody_FullMethodName             = "/proto.TestService/PrintBody"
	TestService_PrintHeaders_FullMethodName          = "/proto.TestService/PrintHeaders"
	TestService_SimulateInternalError_FullMethodName = "/proto.TestService/SimulateInternalError"
	TestService_SimulateConflict_FullMethodName      = "/proto.TestService/SimulateConflict"
	TestService_Proxy_FullMethodName                 = "/proto.TestService/Proxy"
)

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestServiceClient interface {
	CheckActive(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CheckActiveResponse, error)
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	PrintBody(ctx context.Context, in *PrintBodyRequest, opts ...grpc.CallOption) (*PrintBodyResponse, error)
	PrintHeaders(ctx context.Context, in *PrintHeadersRequest, opts ...grpc.CallOption) (*PrintHeadersResponse, error)
	SimulateInternalError(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	SimulateConflict(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Proxy(ctx context.Context, in *ProxyRequest, opts ...grpc.CallOption) (*ProxyResponse, error)
}

type testServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) CheckActive(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CheckActiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckActiveResponse)
	err := c.cc.Invoke(ctx, TestService_CheckActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, TestService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, TestService_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) PrintBody(ctx context.Context, in *PrintBodyRequest, opts ...grpc.CallOption) (*PrintBodyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintBodyResponse)
	err := c.cc.Invoke(ctx, TestService_PrintBody_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) PrintHeaders(ctx context.Context, in *PrintHeadersRequest, opts ...grpc.CallOption) (*PrintHeadersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintHeadersResponse)
	err := c.cc.Invoke(ctx, TestService_PrintHeaders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) SimulateInternalError(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, TestService_SimulateInternalError_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) SimulateConflict(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, TestService_SimulateConflict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) Proxy(ctx context.Context, in *ProxyRequest, opts ...grpc.CallOption) (*ProxyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProxyResponse)
	err := c.cc.Invoke(ctx, TestService_Proxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServiceServer is the server API for TestService service.
// All implementations must embed UnimplementedTestServiceServer
// for forward compatibility.
type TestServiceServer interface {
	CheckActive(context.Context, *Empty) (*CheckActiveResponse, error)
	HealthCheck(context.Context, *Empty) (*HealthCheckResponse, error)
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	PrintBody(context.Context, *PrintBodyRequest) (*PrintBodyResponse, error)
	PrintHeaders(context.Context, *PrintHeadersRequest) (*PrintHeadersResponse, error)
	SimulateInternalError(context.Context, *Empty) (*Empty, error)
	SimulateConflict(context.Context, *Empty) (*Empty, error)
	Proxy(context.Context, *ProxyRequest) (*ProxyResponse, error)
	mustEmbedUnimplementedTestServiceServer()
}

// UnimplementedTestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTestServiceServer struct{}

func (UnimplementedTestServiceServer) CheckActive(context.Context, *Empty) (*CheckActiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckActive not implemented")
}
func (UnimplementedTestServiceServer) HealthCheck(context.Context, *Empty) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedTestServiceServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedTestServiceServer) PrintBody(context.Context, *PrintBodyRequest) (*PrintBodyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrintBody not implemented")
}
func (UnimplementedTestServiceServer) PrintHeaders(context.Context, *PrintHeadersRequest) (*PrintHeadersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrintHeaders not implemented")
}
func (UnimplementedTestServiceServer) SimulateInternalError(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SimulateInternalError not implemented")
}
func (UnimplementedTestServiceServer) SimulateConflict(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SimulateConflict not implemented")
}
func (UnimplementedTestServiceServer) Proxy(context.Context, *ProxyRequest) (*ProxyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Proxy not implemented")
}
func (UnimplementedTestServiceServer) mustEmbedUnimplementedTestServiceServer() {}
func (UnimplementedTestServiceServer) testEmbeddedByValue()                     {}

// UnsafeTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServiceServer will
// result in compilation errors.
type UnsafeTestServiceServer interface {
	mustEmbedUnimplementedTestServiceServer()
}

func RegisterTestServiceServer(s grpc.ServiceRegistrar, srv TestServiceServer) {
	// If the following call panics, it indicates UnimplementedTestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TestService_ServiceDesc, srv)
}

func _TestService_CheckActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).CheckActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_CheckActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).CheckActive(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_PrintBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintBodyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).PrintBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_PrintBody_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).PrintBody(ctx, req.(*PrintBodyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_PrintHeaders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintHeadersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).PrintHeaders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_PrintHeaders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).PrintHeaders(ctx, req.(*PrintHeadersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_SimulateInternalError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).SimulateInternalError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_SimulateInternalError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).SimulateInternalError(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_SimulateConflict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).SimulateConflict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_SimulateConflict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).SimulateConflict(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_Proxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).Proxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_Proxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).Proxy(ctx, req.(*ProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TestService_ServiceDesc is the grpc.ServiceDesc for TestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckActive",
			Handler:    _TestService_CheckActive_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _TestService_HealthCheck_Handler,
		},
		{
			MethodName: "Hello",
			Handler:    _TestService_Hello_Handler,
		},
		{
			MethodName: "PrintBody",
			Handler:    _TestService_PrintBody_Handler,
		},
		{
			MethodName: "PrintHeaders",
			Handler:    _TestService_PrintHeaders_Handler,
		},
		{
			MethodName: "SimulateInternalError",
			Handler:    _TestService_SimulateInternalError_Handler,
		},
		{
			MethodName: "SimulateConflict",
			Handler:    _TestService_SimulateConflict_Handler,
		},
		{
			MethodName: "Proxy",
			Handler:    _TestService_Proxy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
