apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  # +optional Incoming connection details for the component (AKA endpoints).
  inbound:
    # +required Unique name for the endpoint. (This name will be used when generating the managed API)
    - name: ep 0
      # +required Numeric port value that gets exposed via this endpoint
      port: 9090
      # +required Type of the traffic this endpoint is accepting. Example: REST, GraphQL, etc.
      # Allowed values: REST, GraphQL, GRPC
      type: REST
      # +optional Network level visibility of this endpoint. Defaults to Project
      # Accepted values: Project|Organization|Public.
      networkVisibility: Public
      # +optional Context (base path) of the API that is exposed via this endpoint.
      # This is mandatory if the endpoint type is set to REST or GraphQL.
      context: /
      # +optional Path to the schema definition file. Defaults to wild card route if not provided
      # This is only applicable to REST endpoint types.
      # The path should be relative to the docker context.
      schemaFilePath: openapi.yaml
  # +optional Outgoing connection details for the component.
  outbound:
    serviceReferences:
      - name: choreo:///tharinduwijewardane/load-test/nov1-inventory-public/803f0/v1/PUBLIC
        connectionConfig: 01ef983e-9eb7-1938-95f4-0c2fd023face
        env:
          - from: ServiceURL
            to: INVENTORY_SERVICE_URL
          - from: ConsumerKey
            to: INVENTORY_CONSUMER_KEY
          - from: ConsumerSecret
            to: INVENTORY_CONSUMER_SECRET
          - from: TokenURL
            to: INVENTORY_TOKEN_URL
          - from: ChoreoAPIKey
            to: INVENTORY_CHOREO_API_KEY
